# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://effectivealtruismuct.github.io/indabaX-ai-safety-workshop-2023'
baseurl: 'https://effectivealtruismuct.github.io/indabaX-ai-safety-workshop-2023'
title: 'First South African Workshop on AI Safety'
description: '4th of July 2023 @ IndabaX South Africa'
permalink: pretty
logo: "/assets/images/robot_earth.png"

# Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Africa/Johannesburg # Timezone for blog posts and alike

# Header nav
navigation_header:
- title: Home
  url: /
- title: Resources
  url: /resources/
- title: Photos
  url: /photos/

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  32: '/assets/images/robot_earth_32.png'