remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-seo-tag
title: First South African Workshop on AI Safety
description: 14th of July 2023 @ IndabaX South Africa