# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
title: 'First South African Workshop on AI Safety'
description: '4th of July 2023 @ IndabaX South Africa'
permalink: pretty
logo: "/assets/logos/robot_earth.png"

# Header nav
navigation_header:
- title: Home
  url: /
- title: Resources
  url: /resources